service:
  root_username: 'root'
  root_password: 'root_password'
  operator_session_secret_key: 'secret'
  consumer_session_secret_key: 'secret'

database:
  database: 'ayberk-test'
  host: 'localhost'
  port: '27017'
  user: 'root' 
  password: 'password123'

encryption:
  enabled: true
  secret: 'secret'